import Head from "next/head";
import { Open_Sans } from "next/font/google";

import { makeTurnData } from "components/turn";
import Page from "components/page";
import RollGrid from "components/roll-grid";
import Sheet from "components/sheet";
import Sidebar from "components/sidebar";
import TurnGrid from "components/turn-grid";

const font = Open_Sans({ subsets: ["latin"] });

export async function getStaticProps(context) {
  const commit = require("child_process")
    .execSync('git log -n1 --format="%h %ai"')
    .toString()
    .trim();

  const [commitHash, dateString] = commit.split(" ");

  return {
    props: {
      commitHash,
      dateString,
    },
  };
}

function Home({ count, commitHash, dateString }) {
  const turnsData = [
    makeTurnData({
      money: [10],
      A: [0],
      B: [0],
      C: [0],
      D: [0],
      AB: [0],
      ABC: [0],
      ABCD: [0],
      opportunity: [12],
    }),
    makeTurnData({ opportunity: [12] }),
    makeTurnData({ opportunity: [8] }),
    makeTurnData({ opportunity: [8] }),
    makeTurnData({ opportunity: [4] }),
    makeTurnData({ opportunity: [4] }),
  ];

  return (
    <>
      <Head>
        <title>Hardware Hustle</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${font.className}`}>
        <Sheet>
          {[...Array(count || 0)].map((e, i) => (
            <Page split key={i}>
              <Sidebar
                turnsData={turnsData}
                commitHash={commitHash}
                dateString={dateString}
              />
              <TurnGrid turnsData={turnsData} />
            </Page>
          ))}
        </Sheet>
        <Sheet>
          {[...Array(count || 0)].map((e, i) => (
            <Page key={i}>
              <RollGrid columns={35} rows={25} />
            </Page>
          ))}
        </Sheet>
      </main>
    </>
  );
}

Home.defaultProps = {
  count: 1,
  commitHash: undefined,
  dateString: undefined,
};

export default Home;
