import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hardware Hustle</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <table>
          <thead>
            <tr>
              <th></th>
              <th>Buy</th>
              <th>Make</th>
              <th>Sell</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th>
                <i className="bi bi-currency-dollar"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <th>
                <i className="bi bi-bezier2"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>
                <i className="bi bi-box-seam"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>
                <i className="bi bi-hdd-rack"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>
                <i className="bi bi-battery-half"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
          <tbody>
            <tr>
              <th>
                <i className="bi bi-motherboard"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>
                <i className="bi bi-boombox"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <th>
                <i className="bi bi-truck-front"></i>
              </th>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
        </table>
      </main>
    </>
  );
}
